version: '3.9'
services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    restart: always
    container_name: limited-redis
    image: redis:7.2.2-alpine
    ports:
      - '6379:6379'
    volumes: 
      - redis-volume:/data
volumes:
  redis-volume: {}